# Generated by Django 4.2.8 on 2024-01-09 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='donor_photos/')),
                ('units', models.IntegerField(default=0)),
            ],
        ),
    ]
