# Generated by Django 4.2.8 on 2024-01-09 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQueryDonor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
