# Generated by Django 4.2.8 on 2024-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQueryDonor', '0005_alter_donor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
