# Generated by Django 4.2.8 on 2024-01-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQueryDonor', '0007_bloodbankbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='branch_name',
            field=models.CharField(default='Genel', max_length=255),
        ),
    ]
