# Generated by Django 4.2.8 on 2024-01-14 15:52

from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('CreateQueryDonor', '0008_donor_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='town',
            field=models.CharField(max_length=100),
        ),
    ]