# Generated by Django 4.2.8 on 2024-01-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQueryDonor', '0003_alter_donor_email'),
        ('BloodBankManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateQueryDonor.donor'),
        ),
    ]
