# Generated by Django 4.2.8 on 2024-01-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBankManagement', '0003_bloodbank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='branch',
        ),
    ]
